from app import create_app, db
from app.models import KPIDescription

app = create_app()

with app.app_context():
    descriptions = [
        (1, 0, 'No'),
        (1, 1, 'La organización no realiza acciones'),
        (1, 2, 'La organización realiza acciones esporádicas'),
        (1, 3, 'La organización posee un plan de reducción del consumo eléctrico'),
        (1, 4, 'La organización posee un programa de gestión ambiental en donde se contempla la reducción del consumo eléctrico y lo supervisa la más alta autoridad'),
        (2, 0, 'No'),
        (2, 1, 'No posee un programa de gestión ambiental'),
        (2, 2, 'La organización posee un programa de gestión ambiental respetando la normativa ambiental'),
        (2, 3, 'La organización posee un programa de gestión ambiental y posee certificaciones externas (ISO o similar)'),
        (2, 4, 'La organización posee un programa de gestión ambiental y posee certificaciones externas (ISO o similar) y lo supervisa la más alta autoridad'),
        (3, 0, 'No'),
        (3, 1, 'La organización no realiza acciones'),
        (3, 2, 'La organización realiza acciones esporádicas'),
        (3, 3, 'La organización posee un plan de reducción del consumo de agua'),
        (3, 4, 'La organización posee un programa de gestión ambiental en donde se contempla la reducción del consumo de agua y lo supervisa la más alta autoridad'),
        (4, 0, 'No'),
        (4, 1, 'La organización no realiza acciones'),
        (4, 2, 'La organización realiza acciones esporádicas'),
        (4, 3, 'La organización posee un plan de reducción de residuos'),
        (4, 4, 'La organización posee un programa de gestión ambiental en donde se contempla la reducción de residuos y lo supervisa la más alta autoridad'),
        (5, 0, 'No'),
        (5, 1, 'No se dispone de una identificación ni de una definición de temas relevantes relacionados con aspectos ambientales para la actividad de la organización'),
        (5, 2, 'Se ha llevado a cabo una identificación de los temas relevantes para la organización y las áreas de influencia en temas ambientales'),
        (5, 3, 'Además de la identificación de asuntos relevantes, la organización establece planes y objetivos para gestionar los asuntos relevantes identificados'),
        (5, 4, 'La gestión de los asuntos relevantes son una prioridad para la organización y lo supervisa la más alta autoridad'),
        (6, 0, 'No'),
        (6, 1, 'La organización incumple o cumple parcialmente aspectos básicos de la ley laboral'),
        (6, 2, 'La organización cumple la regulación en materia laboral (Estatuto de los trabajadores, Convenio colectivo), Seguridad y Salud, Protección de datos, etc.'),
        (6, 3, 'Además del cumplimiento regulatorio, la empresa establece planes y objetivos para mejorar la gestión de las condiciones laborales (como plan de cero accidentes)'),
        (6, 4, 'Las cuestiones laborales y de desarrollo profesional forman parte de la estrategia de la organización y se supervisan por la máxima autoridad de la organización.'),
        (7, 0, 'No'),
        (7, 1, 'La organización incumple o cumple parcialmente regulación en materia de diversidad, inclusión, discriminación o derechos humanos'),
        (7, 2, 'La organización cumple la regulación y normativa vigente en materia de diversidad e inclusión'),
        (7, 3, 'La organización establece prácticas y objetivos para mejorar la gestión de la diversidad e inclusión que van más allá del cumplimiento regulatorio, estableciendo objetivos de integración de colectivos vulnerables'),
        (7, 4, 'Los asuntos relacionados con diversidad, inclusión y derechos humanos forman parte de la estrategia de la organización y son supervisados por la más alta autoridad'),
        (8, 0, 'No'),
        (8, 1, 'La organización no aborda temas sociales con sus colaboradores internos'),
        (8, 2, 'Los colaboradores internos están involucrados en temas relacionados a voluntarios u otras acciones comunitarias y sociales'),
        (8, 3, 'La máxima autoridad de la Organización impulsa iniciativas de acciones sociales con la comunidad local'),
        (8, 4, 'La organización se comunica de manera amplia con sus colaboradores en temas de sostenibilidad, posee programas estructurados de inversión social e indicadores a largo plazo'),
        (9, 0, 'No'),
        (9, 1, 'La organización incumple la normativa vigente en el cuidado de la salud y seguridad de sus colaboradores'),
        (9, 2, 'La organización cumple la normativa vigente en el cuidado de la salud y seguridad de sus colaboradores'),
        (9, 3, 'La organización posee un sistema de gestión de la salud y la seguridad en el trabajo de sus colaboradores, evaluando riesgos e investigación de accidentes'),
        (9, 4, 'La organización posee un sistema de gestión de la salud y la seguridad en el trabajo de sus colaboradores, evaluando riesgos e investigación de accidentes y posee una certificación externa en su sistema de gestión'),
        (10, 0, 'No'),
        (10, 1, 'La organización no posee un programa de capacitación para sus colaboradores'),
        (10, 2, 'La organización realiza capacitaciones esporádicas a sus colaboradores'),
        (10, 3, 'La organización posee un programa de capacitación para sus colaboradores destinado a mejorar sus aptitudes'),
        (10, 4, 'La organización posee un programa de capacitación para sus colaboradores destinado a mejorar sus aptitudes y realiza evaluaciones periódicas de desempeño'),
        (11, 0, 'No'),
        (11, 1, 'La organización no posee código de ética'),
        (11, 2, 'La organización se encuentra en un proceso de elaboración de su código de ética'),
        (11, 3, 'La organización cuenta con un código de ética no aprobado por la más alta autoridad'),
        (11, 4, 'La organización cuenta con un código de ética aprobado por la más alta autoridad.'),
        (12, 0, 'No'),
        (12, 1, 'En la organización no existe un canal de denuncias ni línea de ética'),
        (12, 2, 'La organización se encuentra en proceso de realización y se está desarrollando un protocolo de gestión'),
        (12, 3, 'Existe un canal interno de denuncias, el cual es manejado por personal de la organización'),
        (12, 4, 'Existe un canal de denuncias o línea de ética administrado por una entidad externa y un protocolo de gestión de las mismas. Se garantiza la confidencialidad de todos los comunicados que se realicen'),
        (13, 0, 'No'),
        (13, 1, 'La organización no cuenta ni con un área ni encargado de Cumplimiento o de Compliance'),
        (13, 2, 'En la organización se está diagramando el área y/o definiendo el responsable'),
        (13, 3, 'La organización cuenta con una persona que se encarga de dichas cuestiones'),
        (13, 4, 'La organización cuenta con un área específica, encargada de la gestión de un programa de Compliance'),
        (14, 0, 'No'),
        (14, 1, 'En la organización no existe un proceso de debida diligencia para conocer a los terceros con los que interactúa'),
        (14, 2, 'La Organización se encuentra en elaboración de un proceso de debida diligencia'),
        (14, 3, 'La organización realiza acciones de debida diligencia pero en forma posterior a la contratación de un tercero'),
        (14, 4, 'La organización realiza un proceso de debida diligencia en forman anterior a la contratación de un tercero'),
        (15, 0, 'No'),
        (15, 1, 'En la organización no se ha realizado una evaluación de riesgos'),
        (15, 2, 'La organización se encuentra en proceso de realización de una evaluación de riesgos'),
        (15, 3, 'La organización cuenta con una evaluación de riesgos pero la misma está incompleta'),
        (15, 4, 'La organización cuenta con una evaluación de riesgos, mediante la cual se establecieron los posibles riesgos que tiene la Compañía al interactuar con distintos terceros'),
        (16, 0, 'No'),
        (16, 1, 'No posee Medición de Huella de Carbono'),
        (16, 2, 'La organización posee Medición de Huella de Carbono alcance 1'),
        (16, 3, 'La organización posee Medición de Huella de Carbono alcance 1 y cuenta con objetivo de reducción'),
        (16, 4, 'La organización posee Medición de Huella de Carbono alcances 1, 2 y 3, cuenta con objetivo, plan de reducción, y, además, cuenta con disminución en su Huella de Carbono')
    ]

    for question_number, value, description in descriptions:
        db.session.add(KPIDescription(question_number=question_number, value=value, description=description))
    
    db.session.commit()
    print("Descripciones insertadas correctamente")